### ISSUE TITLE
Remote update and additional directory

### ISSUE THREAD

**Issue by Shark-vil** [LGuerrero13/gif#2]
https://github.com/LGuerrero13/gif/blob/10ddba55b15bc8e1574f2789d44f7b5fc93c0cf0/gif/Form1.cs#L83

It would be more logical to have a list of standard identifiers in a separate file that could be updated remotely, for example from a fresh raw file in github.

---

https://github.com/LGuerrero13/gif/blob/10ddba55b15bc8e1574f2789d44f7b5fc93c0cf0/gif/Form1.cs#L15

Should consider this folder too:
"SteamLibrary\steamapps\workshop\content\4000"

**Comment by HonestResolv3** [comment]
Regarding the first suggestion in this issue I am working on that (as a .txt file that can be edited on GitHub and retrieved from when the program loads and with a new "Download IDs" button)

The second one I can add that in a separate PR

**Comment by LGuerrero13** [comment]
@HonestResolv3 has made a PR for the first part of the suggestion, and has been proved! It will now automatically fetch workshop IDs from the file hosted here and will be maintained. 🎉 

I will close this issue once we get the second PR for the steam folder approved.

**Comment by LGuerrero13** [comment]
Final PR has been approved! 🎉 I'll be closing this issue.
