### ISSUE TITLE
.EXE Not working

### ISSUE THREAD

**Issue by TheTinkerer256** [LGuerrero13/gif#6]
Hello!
I downloaded the release, unzipped the file, and launched gif.exe, but it doesn't seem to do anything when I run it. I downloaded gif.zip from releases.
Thanks!

**Comment by HonestResolv3** [comment]
Do you receive any errors when you are loading up the .exe? I loaded the .exe file seen in "gif-v.1.2.zip" and I can confirm that it is working as intended on Windows 10

It downloads the ID's from GitHub then doing a scan shows if there is/isn't any infected addons

**Comment by LGuerrero13** [comment]
I believe I probably might’ve compiled it in Debug mode and uploaded it, instead of release mode. I will fix that as soon as I’m able to!

**Comment by TheTinkerer256** [comment]
@HonestResolv3, nothing even pops up, it's like double-clicking on blank space. The zip file had all the files in it in a folder called net6.0-windows.
and @LGuerrero13, please tell me when this is fixed.

Thank you both!

**Comment by LGuerrero13** [comment]
@TheTinkerer256  I have approved the PR and updated the release download to make sure it's in release mode. Please let me know if it still doesn't work.

**Comment by TheTinkerer256** [comment]
Nope, still nothing, same result as before

**Comment by LGuerrero13** [comment]
Make sure you have Microsoft .NET 6.0 installed. [https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore](https://steamcommunity.com/linkfilter/?url=https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore)
(click either "Download x64" or "Download x86" depending on your OS, under "Run desktop apps")

If that still isn't pointing you in the right direction, run the app from a command window. Any exception should get printed to the command window and will remain open for you to examine

**Comment by TheTinkerer256** [comment]
That worked, thanks for your help!
